apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-webapp
spec:
  selector:
    matchLabels:
      app: mvn-webapp
  template:
    metadata:
      labels:
        app: mvn-webapp
    spec:
      containers:
      - name: mvn-webapp
        image: snana/mymvn-app:15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mvn-webapp
spec:
  selector:
    app: mvn-webapp
  ports:
  - port: 7070
    targetPort: 8080

